### PR TITLE
Added capability of setting HTTP headers.

### PR DESCRIPTION
**Pull request by programmador**
var cr = new Curl("http://somesite.com/somefile.php");
  var headers : Array<String> = new Array();
  headers.push("Content-type: text/xml;charset=\"utf-8\"");
  cr.setHttpHeaders(headers);

### CODE REVIEW

**Comment by programmador** [comment]
В Tue, 28 Jun 2011 17:10:48 -0700
knarf-se
reply@reply.github.com
пишет:

> Thanx, I trust your changes. Having a little problem getting haxe +
> neko running over here.
> 
> Have been sitting here for several hours getting everything up and
> running (Had a weird total system crash on my Ubuntu after system
> update), and out of the blue, neko seems to loose its ability to read
> files.
> 
> >  **~/prj/hxCurl/tmp $** neko run_tests.neko
> >  Uncaught exception - load.c(176) : Module not found :
> > run_tests.neko **~/prj/hxCurl/tmp $** ls
> >  curlw.o  curl_wrap.ndll  Linux  run_tests.neko  Server.js
> 
> I really wounder what went wrong, it was working like 2 secs ago

I had a similar problem. I have my haxelib folder in /home/<ME>/.haxe .
When I tried to run it under webserver - it's working with rights of
user www-data - so it doesn't know where haxelib folder is and even if
it would - it still couldn't open ndll because user www-data doesn't
have rights to read files from home/<ME>. The solution was to put
curl_wrap.ndll into /usr/lib/neko where other ndlls (such as
mysql.ndll) are situated.

But it seems like You have problems even if You run it as Your user,
not as www-data.

Also I think that it's time to share hxCurl at lib.haxe.org - v.0.2 or
smth like that. Of course if You're not too busy. BTW, how's Your
business? You was talking about opening a firm.

**Comment by programmador** [comment]
I've just downloaded a new version from git. I've installed nodejs
package and run ./build:

fashist@jager:~/Загрузки/hxCurl$ ./build
→ Building hxCurl
Successfully created Neko FFI module 'curl_wrap.ndll'
→ Building Unittests
cp: невозможно выполнить stat для «Server.js»: Нет такого файла или
каталога → Running Unittests

node.js:134
        throw e; // process.nextTick error, or 'error' event on first
tick ^
Error: Cannot find module '/home/fashist/Загрузки/hxCurl/tmp/Server.js'
    at Function._resolveFilename (module.js:322:11)
    at Function._load (module.js:267:25)
    at Array.<anonymous> (module.js:426:10)
    at EventEmitter._tickCallback (node.js:126:26)
→ Assembling the 'release.zip' package
Invalid commandline class : Curl should be curl.Curl
  Created Source/
  Install Source/curl_wrap.c
  Created curl/
  Install curl/Curl.hx
  Install haxelib.xml
  Created ndll/
  Created ndll/Linux/
  Install ndll/Linux/curl_wrap.ndll
  Current version is now 0.1.1
Done

But ndll is being built well.

P.S. Translation of output:
невозможно выполнить = unable to do/make/run/etc...
Нет такого файла или каталога = No such file or directory

**Comment by knarf-se** [comment]
Weird, looks like the answers I mailed back from my phone did not show up here? Well, anyways I got my WiFi working seconds ago (Note to myself **sudo rfkill unblock all**) so the file ‘tests/Server.js’ should be there in the repo now (Note to myself **-a** does not add all files in CWD and / or subdirs).

**Comment by programmador** [comment]
В Thu, 30 Jun 2011 13:43:02 -0700
knarf-se
reply@reply.github.com
пишет:

> Weird, looks like the answers I mailed back from my phone did not
> show up here? Well, anyways I got my WiFi working seconds ago (Note
> to myself **sudo rfkill unblock all**) so the file ‘tests/Server.js’
> should be there in the repo now (Note to myself **-a** does not add
> all files in CWD and / or subdirs).

Yeah, I have the same problem while sending a message from my phone -
looks like it doesn't work with message id.

## Tests are now OK, but I get this message:

→ Generating API reference documentation

##     Did not find chxdoc, won't generate API reference documentation

even after installing chxdoc.

**Comment by knarf-se** [comment]
Ah, okay. So github just redirected my massages to /dev/null ? ;-)

For the documentation to work, the files 'chxdoc' and 'temploc' must be in the basedirectory of hxCurl, that is what 'haxelib run chxdoc install' does.

**Comment by programmador** [comment]
В Fri, 1 Jul 2011 01:57:04 -0700
knarf-se
reply@reply.github.com
пишет:

> Ah, okay. So github just redirected my massages to /dev/null ? ;-)
> 
> For the documentation to work, the files 'chxdoc' and 'temploc' must
> be in the basedirectory of hxCurl, that is what 'haxelib run chxdoc
> install' does.

Are You talking about this message?
From: knarf-se noreply@github.com
To: alexander.konotop@gmail.com
Subject: knarf-se added you to hxCurl
Date: Tue, 28 Jun 2011 18:59:42 -0700

You can now push to this repository.

## 

Reply to this email directly or view it on GitHub:
https://github.com/knarf-se/hxCurl

And thanks, hxdoc now works :-)

**Pull request merged**
